name: futureagi-dpo
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - torchaudio==2.5.1+cu121
      - transformers==4.52.3
      - trl==0.19.0
      - datasets==3.6.0
      - accelerate==1.8.1
      - safetensors==0.5.3
      - huggingface-hub==0.32.2
